// Cool Careers page copy. The program overview is taken from the "Cool Careers
// One-Pager" in the Cool Careers Pilot Pitch Claude Design project. Spanish is
// an unofficial rendering — see CONTENT_NEEDED.md.
export const ccCopy = {
  en: {
    nav_home: "Home",
    nav_cta: "Book a pilot demo",
    hero_title: "Play a game. Find a future.",
    hero_title_b: "One class period.",
    hero_band: [["Standards-aligned", "marigold"], [", ", null], ["zero-student-data", "sky"], [", ", null], ["CTE-funded", "leaf"], [" career exploration that plugs into an existing class period.", null]],
    hero_portal: "Open the game portal",
    hero_caption: "Felt school buses charging up on sun and wind.",

    why_label: "WHY NOW",
    why: [
      { n: "3×", hue: "leaf", text: "Clean energy jobs grew 3× faster than the rest of the US economy last year — nearly 100,000 new jobs", src: "US DOE, USEER 2025" },
      { n: "7 in 8", hue: "sky", text: "workers worldwide lack even a single green skill — green hiring grows nearly 2× as fast as green talent", src: "LinkedIn Global Green Skills Report 2025" },
      { n: "1 in 3", hue: "coral", text: "new US energy jobs in recent years have gone to Latino/Hispanic workers — and 29% of the energy workforce is under 30", src: "US DOE, USEER 2025" },
    ],
    students_label: "WHAT STUDENTS DO",
    students: [
      ["Play", " a 2-player digital card game about real regenerative careers"],
      ["Tell", " their own nature story"],
      ["Reveal", " their career avatar"],
      ["Follow real pathways", " — videos, programs, internships & mentors on 100+ career cards"],
    ],
    students_foot: "100+ cards, mapped to National Career Clusters.",
    pipeline: "This pipeline starts in class.",
    teachers_label: "WHAT TEACHERS GET",
    teachers: [
      ["45·50·60·90", "auto-paced lesson plan for your period length", "leaf"],
      ["2 min", "projected join code — students in fast", "sky"],
      ["Run-of-Show", "session guide keeps the period on track", "marigold"],
      ["1-click", "share to Google Classroom", "coral"],
      ["Map", "Standards Map shows what each session covers", "leaf"],
      ["Pre / post", "automatic reflection capture for your report", "sky"],
    ],
    district_label: "BUILT FOR DISTRICT APPROVAL",
    district: [
      ["Zero student PII", " — class code + nickname; no student emails or accounts"],
      ["FERPA / COPPA-friendly", " by design — essentially nothing to review"],
      ["District-safe curated resources", " — PBS, .gov, .edu prioritized; every link auto-checked monthly"],
      ["WCAG 2.1 AA", " accessibility options — text size, high contrast, reduced motion"],
      ["National Career Clusters aligned", " — CTE program integration, Perkins V & workforce-grant eligible"],
    ],
    pilot_title: "Pilot free with one class period —",
    pilot_hi: " 2026–27 cohort now booking.",
    pilot_sub: "Santa Fe & Albuquerque districts piloting",

    video_title: "Cool Careers",
    video_sub: "Workforce Development for Sustainability",
    video_play: "Play the Cool Careers music video",

    portal_label: "THE GAME PORTAL",
    portal_title: "Step inside the game.",
    portal_sub: "Students set up an explorer profile, link up with a classmate to play, meet their career avatar, and ride the Green Line — no accounts, no student data.",
    portal_points: ["Set up your explorer profile", "Play the Game", "Build Your Cool Career", "Ride the Green Line"],
    portal_btn: "Enter the game portal",

    cta_head: "Bring Cool Careers to your school.",
    cta_sub: "One class period. Zero student data. A pipeline that starts in class.",
    cta_btn: "Book a pilot demo",
    footer: "ALL ABOARD EARTH · UP WE GO! 🌱",
    give: "Donations are held for us by our fiscal sponsor,",
  },
  es: {
    nav_home: "Inicio",
    nav_cta: "Reserva una demo",
    hero_title: "Juega. Encuentra un futuro.",
    hero_title_b: "Una sola clase.",
    hero_band: [["Alineado a estándares", "marigold"], [", ", null], ["cero datos estudiantiles", "sky"], [", ", null], ["financiable por CTE", "leaf"], [": exploración de carreras que se integra a una clase existente.", null]],
    hero_portal: "Abre el portal del juego",
    hero_caption: "Autobuses escolares de fieltro cargándose con sol y viento.",

    why_label: "POR QUÉ AHORA",
    why: [
      { n: "3×", hue: "leaf", text: "Los empleos en energía limpia crecieron 3× más rápido que el resto de la economía de EE. UU. el año pasado — casi 100,000 empleos nuevos", src: "US DOE, USEER 2025" },
      { n: "7 de 8", hue: "sky", text: "trabajadores en el mundo no tienen ni una sola habilidad verde — la contratación verde crece casi 2× más rápido que el talento verde", src: "LinkedIn Global Green Skills Report 2025" },
      { n: "1 de 3", hue: "coral", text: "nuevos empleos energéticos en EE. UU. en años recientes fueron para trabajadores latinos/hispanos — y el 29% de la fuerza laboral energética tiene menos de 30 años", src: "US DOE, USEER 2025" },
    ],
    students_label: "LO QUE HACEN LOS ESTUDIANTES",
    students: [
      ["Juegan", " un juego de cartas digital para 2 jugadores sobre carreras regenerativas reales"],
      ["Cuentan", " su propia historia con la naturaleza"],
      ["Descubren", " su avatar de carrera"],
      ["Siguen rutas reales", " — videos, programas, pasantías y mentores en más de 100 cartas de carreras"],
    ],
    students_foot: "Más de 100 cartas, alineadas a los National Career Clusters.",
    pipeline: "Esta ruta empieza en el salón.",
    teachers_label: "LO QUE RECIBEN LOS MAESTROS",
    teachers: [
      ["45·50·60·90", "plan de clase con ritmo automático para la duración de tu periodo", "leaf"],
      ["2 min", "código de acceso proyectado — los estudiantes entran rápido", "sky"],
      ["Guion", "guía de sesión que mantiene la clase en tiempo", "marigold"],
      ["1 clic", "comparte en Google Classroom", "coral"],
      ["Mapa", "el Mapa de Estándares muestra qué cubre cada sesión", "leaf"],
      ["Pre / post", "captura automática de reflexiones para tu informe", "sky"],
    ],
    district_label: "HECHO PARA LA APROBACIÓN DEL DISTRITO",
    district: [
      ["Cero datos personales", " — código de clase + apodo; sin correos ni cuentas de estudiantes"],
      ["Compatible con FERPA / COPPA", " desde el diseño — prácticamente nada que revisar"],
      ["Recursos curados y seguros", " — prioridad a PBS, .gov y .edu; cada enlace se revisa automáticamente cada mes"],
      ["WCAG 2.1 AA", " opciones de accesibilidad — tamaño de texto, alto contraste, movimiento reducido"],
      ["Alineado a National Career Clusters", " — integración con programas CTE, elegible para Perkins V y fondos laborales"],
    ],
    pilot_title: "Piloto gratis con una sola clase —",
    pilot_hi: " inscripciones abiertas para 2026–27.",
    pilot_sub: "Distritos de Santa Fe y Albuquerque en piloto",

    video_title: "Cool Careers",
    video_sub: "Desarrollo laboral para la sostenibilidad",
    video_play: "Reproducir el video musical de Cool Careers",

    portal_label: "EL PORTAL DEL JUEGO",
    portal_title: "Entra al juego.",
    portal_sub: "Los estudiantes crean su perfil de explorador, se conectan con un compañero para jugar, conocen su avatar de carrera y viajan en la Línea Verde — sin cuentas, sin datos estudiantiles.",
    portal_points: ["Crea tu perfil de explorador", "Juega", "Construye tu Cool Career", "Viaja en la Línea Verde"],
    portal_btn: "Entra al portal del juego",

    cta_head: "Lleva Cool Careers a tu escuela.",
    cta_sub: "Una clase. Cero datos estudiantiles. Una ruta que empieza en el salón.",
    cta_btn: "Reserva una demo",
    footer: "ALL ABOARD EARTH · ¡ARRIBA VAMOS! 🌱",
    give: "Las donaciones las administra nuestro patrocinador fiscal,",
  },
};
